# -> Latest version of docker-compose
version: '3.3'

services:
    nginx:
        depends_on:
            - wordpress
        build: requirements/nginx/
        image: nginx_img
        container_name: nginx
        ports:
            - "443:443"
        networks:
            - inception
        volumes:
            - volume_wordpress:/var/www/html
        restart: unless-stopped

    wordpress:
        depends_on:
            - mariadb
        env_file:
            - .env
        build: requirements/wordpress/
        image: wp_img
        container_name: wp
        expose:
            - "3306"
        networks:
            - inception
        volumes:
            - volume_wordpress:/var/www/html
        restart: on-failure

    mariadb:
        env_file:
            - .env
        build: requirements/mariadb/
        image: mariadb_img
        container_name: mariadb
        expose:
            - "9000"
        networks:
            - inception
        volumes:
            - volume_mariadb:/var/lib/mysql
        restart: on-failure

networks:
    inception:
        driver: bridge

volumes:
    volume_mariadb:
        driver: local
        driver_opts:
            o: 'bind'
            type: 'none'
            device: '/home/mmondell/data/mariadb'

    volume_wordpress:
        driver: local
        driver_opts:
            o: 'bind'
            type: 'none'
            device: '/home/mmondell/data/wordpress'
