# -> Latest version of docker-compose
version: '3'

services:
    nginx:
        depends_on:
            - wordpress
        build: requirements/nginx/
        image: nginx_img
        container_name: nginx_cont
        ports:
            - "443:443"
        networks:
            - inception
        volumes:
            - /home/mmondell/data/wordpress:/var/www/html
        restart: unless-stopped
    
    wordpress:
        depends_on:
            - mariadb
        build:
            context: requirements/wordpress/
            args:
                DOMAIN_NAME: ${DOMAIN_NAME}
                MARIA_DB_USER: ${MARIA_DB_USER}
                MARIA_DB_USER_PWD: ${MARIA_DB_USER_PWD}
                DB_SERVER: ${DB_SERVER}
                WORDPRESS_ADMIN: ${WORDPRESS_ADMIN}
                WORDPRESS_ADMIN_PWD: ${WORDPRESS_ADMIN_PWD}
                WORDPRESS_USER: ${WORDPRESS_USER}
                WORDPRESS_USER_PWD: ${WORDPRESS_USER_PWD}
        image: wp_img
        container_name: wp_cont
        expose:
            - "3306"
        networks:
            - inception
        volumes:
            - ~/data/wordpress:/var/www/html
        env_file:
            - .env
        environment:
            - DOMAIN_NAME=${DOMAIN_NAME}
            - MARIA_DB_USER=${MARIA_DB_USER}
            - MARIA_DB_USER_PWD=${MARIA_DB_USER_PWD}
            - DB_SERVER=${DB_SERVER}
            - WORDPRESS_ADMIN=${WORDPRESS_ADMIN}
            - WORDPRESS_ADMIN_PWD=${WORDPRESS_ADMIN_PWD}
            - WORDPRESS_USER=${WORDPRESS_USER}
            - WORDPRESS_USER_PWD=${WORDPRESS_USER_PWD}
        restart: on-failure

    mariadb:
        build: requirements/mariadb
        image: mariadb_img
        container_name: mariadb_cont
        expose:
            - "9000"
        networks:
            - inception
        volumes:
            - ~/data/mariadb:/var/lib/mysql
        env_file:
            - .env
        environment:
            - MARIA_DB_USER=${MARIA_DB_USER}
            - MARIA_DB_USER_PWD=${MARIA_DB_USER_PWD}
            - DB_SERVER=${DB_SERVER}
            - MARIA_DB_NEW_ROOT_PWD=${MARIA_DB_NEW_ROOT_PWD}
        restart: on-failure

networks:
    inception:
#        name: inception
        driver: bridge

volumes:
    volume_mariadb: 
        driver: local
        driver_opts:
            o: 'bind'
            type: 'none'
            device: '~/Documents/inception/volumes'
    
    volume_wordpress:
        driver: local
        driver_opts:
            o: 'bind'
            type: 'none' 
            device: '~/Documents/inception/volumes'
